global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
- job_name: blackbox # To get metrics about the exporter itself
  metrics_path: /actuator/prometheus
  static_configs:
    - targets:
      - localhost: 8081
	  - localhost: 8082
	  - localhost: 8083