{
 "title": "Resilience4j",
 "description": "Resilience4j Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state, instance)"
    }
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state, name)"
    }
   },
   {
    "name": "retry_name",
    "label": "Retry Name",
    "query": {
     "query": "label_values(resilience4j_retry_calls, name)"
    }
   },
   {
    "name": "bulkhead_name",
    "label": "Bulkead Name",
    "query": {
     "query": "label_values(resilience4j_bulkhead_available_concurrent_calls, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of closed CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"closed\"})"
    }
   ]
  },
  {
   "title": "Number of open CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=~\"open|forced_open\"})"
    }
   ]
  },
  {
   "title": "Number of half_open CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"half_open\"})"
    }
   ]
  },
  {
   "title": "CircuitBreaker States",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{instance=\"192.168.1.200:8081\"}",
     "legendFormat": "{{ name }}: {{ state }}"
    }
   ]
  },
  {
   "title": "CircuitBreaker States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{instance=\"192.168.1.200:8083\"}",
     "legendFormat": "{{ name }}: {{ state }}"
    }
   ]
  },
  {
   "title": "CircuitBreaker States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{instance=\"192.168.1.200:8082\"}",
     "legendFormat": "{{ name }}: {{ state }}"
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "circuitbreaker_name" },
  {
   "title": "Failure Rate: ticketingService",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{instance=\"192.168.1.200:8081\",name=\"ticketingService\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Failure Rate: customerService",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{instance=\"192.168.1.200:8081\",name=\"customerService\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Failure Rate: customerdb",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{instance=\"192.168.1.200:8082\",name=\"customerdb\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Failure Rate: ticketingdb",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{instance=\"192.168.1.200:8083\",name=\"ticketingdb\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name customerService",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Call rate: ticketingService",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8081\",name=\"ticketingService\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{instance=\"192.168.1.200:8081\",name=\"ticketingService\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Call rate: customerdb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8082\",name=\"customerdb\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{instance=\"192.168.1.200:8082\",name=\"customerdb\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Call rate: ticketingdb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8083\",name=\"ticketingdb\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{instance=\"192.168.1.200:8083\",name=\"ticketingdb\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Buffered calls: customerService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{instance=\"192.168.1.200:8081\",name=\"customerService\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{instance=\"192.168.1.200:8081\",name=\"customerService\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Buffered calls: ticketingService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{instance=\"192.168.1.200:8081\",name=\"ticketingService\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{instance=\"192.168.1.200:8081\",name=\"ticketingService\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Buffered calls: customerdb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{instance=\"192.168.1.200:8082\",name=\"customerdb\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{instance=\"192.168.1.200:8082\",name=\"customerdb\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Buffered calls: ticketingdb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{instance=\"192.168.1.200:8083\",name=\"ticketingdb\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{instance=\"192.168.1.200:8083\",name=\"ticketingdb\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Average call durations - customerService",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  {
   "title": "Average call durations - customerService",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  {
   "title": "Average call durations - customerService",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  {
   "title": "Average call durations - customerService",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{instance=\"192.168.1.200:8081\",name=\"customerService\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  { "title": "Bulkhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 }, "repeat": "bulkhead_name" },
  {
   "title": "Bulkhead: $bulkhead_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_bulkhead_available_concurrent_calls{application=\"$application\",name=\"$bulkhead_name\"}",
     "legendFormat": "Available Calls"
    },
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{application=\"$application\",name=\"$bulkhead_name\"}",
     "legendFormat": "Max allowed Calls"
    }
   ]
  }
 ]
}